---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: wzhou08817/pipeline
    tag: '2.0'

inputs:
  - name: switch-conf-file-generator

run:
  path: bash
  args:
  - -exc
  - |
    ls -lR
    cd ./switch-conf-file-generator
    ansible-playbook main.yml -e "@configs/backhaul_switch_config.yml"
